# Generated by Django 3.0.5 on 2020-08-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200803_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_description',
            field=models.TextField(default=''),
        ),
    ]
