# Generated by Django 3.0.5 on 2020-09-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200803_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_description',
            field=models.TextField(default='~'),
        ),
    ]
