# Generated by Django 3.0.5 on 2020-08-02 15:48

from django.db import migrations, models
import django.utils.timezone
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('temple_name', models.CharField(max_length=64)),
                ('project_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('decription', models.TextField()),
                ('tel', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='a1.jpeg', upload_to=web.models.upload_path)),
                ('expected', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('current_balance', models.FloatField(default=0)),
            ],
        ),
    ]
