# Generated by Django 3.0.5 on 2020-08-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='project_pic'),
        ),
    ]
