# Generated by Django 3.0.5 on 2020-08-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200803_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='default_project.png', null=True, upload_to='project_pic'),
        ),
    ]
