# Generated by Django 3.0.5 on 2020-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_activity_credit_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='project_desc',
            field=models.TextField(default=''),
        ),
    ]
