# Generated by Django 3.0.5 on 2020-08-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_activity_project_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_image',
            field=models.ImageField(default='default_project.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user_image',
            field=models.ImageField(default='default_project.png', upload_to=''),
        ),
    ]
