# Generated by Django 3.0.5 on 2020-08-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200803_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user_image',
        ),
    ]
