# Generated by Django 3.0.5 on 2020-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200803_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_image',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user_image',
            field=models.CharField(max_length=64),
        ),
    ]
