# Generated by Django 3.0.5 on 2020-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200804_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
